# CREATE TABLE "recrutement" (
# 	"id"	INTEGER NOT NULL UNIQUE,
# 	"id_discord"	INTEGER NOT NULL UNIQUE,
# 	"pseudo_ingame"	TEXT NOT NULL UNIQUE,
# 	"annee_naissance"	INTEGER NOT NULL,
# 	"experience"	TEXT NOT NULL,
# 	"grade"	INTEGER NOT NULL DEFAULT 0,
# 	"pays"	TEXT,
# 	"date_recrutement"	NUMERIC NOT NULL,
# 	"has_done_player_info"	NUMERIC NOT NULL DEFAULT 0,
# 	"statut_maison"	INTEGER NOT NULL DEFAULT 0,
# 	"donations"	INTEGER NOT NULL DEFAULT 0,
# 	"constructions"	INTEGER NOT NULL DEFAULT 0,
# 	"double_compte"	INTEGER NOT NULL DEFAULT 0,
# 	"participation_animation"	INTEGER NOT NULL DEFAULT 0,
# 	"<creer_animation"	INTEGER NOT NULL DEFAULT 0,
# 	"nb_recrutement"	INTEGER NOT NULL DEFAULT 0,
# 	"absence_fin"	TEXT,
# 	"last_connection"	INTEGER NOT NULL DEFAULT 0,
# 	"anciennete"	INTEGER NOT NULL DEFAULT 0,
# 	"schematique"	TEXT,
# 	"peut_quitter_pays"	INTEGER NOT NULL DEFAULT 0,
# 	PRIMARY KEY("id" AUTOINCREMENT)
# )